agents:
  queue: "default"

steps:
  - label: "build and push docker image"
    plugins:
      - docker#v3.6.0:
          login: true
      - command: "docker build -t nodeapp:v1 ."
      - command: "docker push pradong/nodeapp:v1"