env:
  USERNAME: "pradong"
  PASSWORD: "9482465919"

steps:
  - lable: "build and push docker image"
    command:
      - "docker build -t nodeapp:v1 ./Dockerfile"
      - "docker login -u $USERNAME -p $PASSWORD"
      - "docker push nodeapp:v1"