agents:
  queue: "default"

steps:
  - label: "build and push docker image"
    plugins:
      - docker-login#v2.0.1:
          username: "pradong"
          password: "9482465919"
  - command: "docker build -t nodeapp:v1 ."
  - command: "docker push pradong/nodeapp:v1"