agents:
  queue: "default"

steps:
  - label: "build and push docker image"
    plugins:
      - docker#v3.6.0:
          build: "./Dockerfile"
          image: "nodeapp:v1"
          registry: "index.docker.io/pradong/app_images"
          login: true